//ARRAY IS RESIZABLE AND MIX DATATYPE ELEMENTS CAN BE PRESENT IN A SINGLE ARRAY
SHALLOW COYIES -> PROPERTIES SHARE THE SAME REFRENCE 
DEEP COPIES -> PROPERTIES DO NOT SHARE THE SAME REFERENCES

const myarr=[3,6,9,true,"vivek"]
console.log(myarr[0])